---
name: Runs the checks for each project and on the ci files
on:
  push:

jobs:
  check:
    name: Linting and Type Checking
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Run checks
        run: ./checks.py
        shell: python
...
